import React from "react";
import "./App.css";
import "antd/dist/antd.css";

import Amplify, { API, Auth } from "aws-amplify";
// file generated by the sls plugin
import awsconfig from "./aws-exports";
import { withAuthenticator } from "aws-amplify-react";

import { BrowserRouter as Router, Switch, Route, Link } from "react-router-dom";

import { Layout, Menu, message, notification } from "antd";
import Problem from "./Problem";
import About from "./About";
import ResetForm from "./ResetForm";

const { Header, Content, Footer } = Layout;

Amplify.configure(awsconfig);

function App() {
  const logout = () => {
    Auth.signOut();
  };

  const nextCtr = () => {
    const key = "updatable";
    message.loading({ content: "Loading...", key });
    API.get(
      "ApiGatewayRestApi", // function defined in our serverless.yml
      "/next", // the function's path
      { responseType: "text" }
    )
      .then((data) => {
        notification.success({
          message: "Notification",
          description: "Next value: " + data.next,
          onClick: () => {
            console.log("Notification Clicked!");
          },
        });
        message.destroy();
      })
      .catch((err) => {
        message.error({
          content: "Failed to generate next value",
          key,
          duration: 2,
        });
      });
  };

  const currentCtr = () => {
    const key = "updatable";

    message.loading({ content: "Loading...", key });
    API.get(
      "ApiGatewayRestApi", // function defined in our serverless.yml
      "/current", // the function's path
      { responseType: "text" }
    )
      .then((response) => {
        notification.success({
          message: "Notification",
          description: "Current value set to: " + response.current,
          onClick: () => {
            console.log("Notification Clicked!");
          },
        });
        message.destroy();
      })
      .catch((err) => {
        message.error({
          content: "Failed to get current value",
          key,
          duration: 2,
        });
      });
  };

  return (
    <Router>
      <Layout className="layout">
        <Header>
          <div className="logo" />
          <Menu theme="dark" mode="horizontal" defaultSelectedKeys={["1"]}>
            <Menu.Item key="1">
              <Link to="/">Home</Link>
            </Menu.Item>
            <Menu.Item key="2" onClick={currentCtr}>
              Current Counter
            </Menu.Item>
            <Menu.Item key="3" onClick={nextCtr}>
              Next Counter
            </Menu.Item>
            <Menu.Item key="4">
              <Link to="/reset">Reset Counter</Link>
            </Menu.Item>
            <Menu.Item key="5">
              <Link to="/about">Tools Used</Link>
            </Menu.Item>
            <Menu.Item key="6" onClick={logout}>
              Logout
            </Menu.Item>
          </Menu>
        </Header>
        <Content style={{ padding: "0 50px" }}>
          <div className="site-layout-content">
            <Switch>
              <Route path="/reset">
                <ResetForm />
              </Route>
              <Route path="/about">
                <About />
              </Route>
              <Route path="/">
                <Problem />
              </Route>
            </Switch>
          </div>
        </Content>
        <Footer style={{ textAlign: "center" }}>
          Ant Design ©2018 Created by Ant UED
        </Footer>
      </Layout>
    </Router>
  );
}

export default withAuthenticator(App);
